export const options = [
  {
    id: 1,
    name: "John Doe",
    address: "123 Main St, City A",
    active: true,
    value: "john-doe",
    label: "John Doe",
    description: "A loyal customer from City A",
    checked: true,
  },
  {
    id: 2,
    name: "Jane Smith",
    address: "456 Elm St, City B",
    active: false,
    value: "jane-smith",
    label: "Jane Smith",
    description: "New customer from City B",
    checked: false,
  },
  {
    id: 3,
    name: "Alice Johnson",
    address: "789 Oak St, City C",
    active: true,
    value: "alice-johnson",
    label: "Alice Johnson",
    description: "Long-time customer from City C",
    checked: true,
  },
  {
    id: 4,
    name: "Michael Brown",
    address: "234 Maple St, City D",
    active: true,
    value: "michael-brown",
    label: "Michael Brown",
    description: "Frequent shopper from City D",
    checked: false,
  },
  {
    id: 5,
    name: "Emily Davis",
    address: "567 Pine St, City E",
    active: false,
    value: "emily-davis",
    label: "Emily Davis",
    description: "Occasional buyer from City E",
    checked: true,
  },
  {
    id: 6,
    name: "William Wilson",
    address: "890 Birch St, City F",
    active: true,
    value: "william-wilson",
    label: "William Wilson",
    description: "Regular customer from City F",
    checked: false,
  },
  {
    id: 7,
    name: "Sophia Taylor",
    address: "123 Cedar St, City G",
    active: true,
    value: "sophia-taylor",
    label: "Sophia Taylor",
    description: "City G's favorite shopper",
    checked: true,
  },
  {
    id: 8,
    name: "James Jackson",
    address: "456 Willow St, City H",
    active: false,
    value: "james-jackson",
    label: "James Jackson",
    description: "Infrequent visitor from City H",
    checked: false,
  },
  {
    id: 9,
    name: "Olivia Harris",
    address: "789 Rose St, City I",
    active: true,
    value: "olivia-harris",
    label: "Olivia Harris",
    description: "City I's enthusiastic buyer",
    checked: true,
  },
  {
    id: 10,
    name: "Ethan Martinez",
    address: "234 Cherry St, City J",
    active: true,
    value: "ethan-martinez",
    label: "Ethan Martinez",
    description: "Avid shopper from City J",
    checked: false,
  },
  {
    id: 11,
    name: "Ava Anderson",
    address: "567 Birch St, City K",
    active: false,
    value: "ava-anderson",
    label: "Ava Anderson",
    description: "Occasional customer from City K",
    checked: true,
  },
  {
    id: 12,
    name: "Noah Nelson",
    address: "890 Maple St, City L",
    active: true,
    value: "noah-nelson",
    label: "Noah Nelson",
    description: "City L's preferred buyer",
    checked: false,
  },
  {
    id: 13,
    name: "Isabella White",
    address: "123 Pine St, City M",
    active: true,
    value: "isabella-white",
    label: "Isabella White",
    description: "Dedicated shopper from City M",
    checked: true,
  },
  {
    id: 14,
    name: "Liam Thompson",
    address: "456 Cedar St, City N",
    active: false,
    value: "liam-thompson",
    label: "Liam Thompson",
    description: "City N's infrequent buyer",
    checked: false,
  },
  {
    id: 15,
    name: "Mia Garcia",
    address: "789 Willow St, City O",
    active: true,
    value: "mia-garcia",
    label: "Mia Garcia",
    description: "Frequent visitor from City O",
    checked: true,
  },
  {
    id: 16,
    name: "Benjamin Moore",
    address: "234 Rose St, City P",
    active: true,
    value: "benjamin-moore",
    label: "Benjamin Moore",
    description: "Loyal customer from City P",
    checked: false,
  },
  {
    id: 17,
    name: "Emma Hall",
    address: "567 Cherry St, City Q",
    active: false,
    value: "emma-hall",
    label: "Emma Hall",
    description: "City Q's occasional shopper",
    checked: true,
  },
  {
    id: 18,
    name: "Alexander Ward",
    address: "890 Birch St, City R",
    active: true,
    value: "alexander-ward",
    label: "Alexander Ward",
    description: "Regular buyer from City R",
    checked: false,
  },
  {
    id: 19,
    name: "Aria Foster",
    address: "123 Cedar St, City S",
    active: true,
    value: "aria-foster",
    label: "Aria Foster",
    description: "City S's valued customer",
    checked: true,
  },
  {
    id: 20,
    name: "Daniel Simmons",
    address: "456 Willow St, City T",
    active: false,
    value: "daniel-simmons",
    label: "Daniel Simmons",
    description: "Occasional shopper from City T",
    checked: false,
  }
];


